//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meat_and_Milk_and__price.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Price_AccountEntities : DbContext
    {
        public Price_AccountEntities()
            : base("name=Price_AccountEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Combines> Combines { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Product_Group> Product_Group { get; set; }
        public virtual DbSet<Products> Products { get; set; }
    }
}
