//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meat_and_Milk_and__price.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sort { get; set; }
        public Nullable<int> Id_Product_Group { get; set; }
        public Nullable<int> Id_Combines { get; set; }
    
        public virtual Combines Combines { get; set; }
        public virtual Product_Group Product_Group { get; set; }
    }
}
